### ISSUE TITLE
Registration - Forgot Password

### ISSUE THREAD

**Issue by dhaist** [COSC481W-2022Fall/capstone-project-vibe#63]
**Description**
Given that the user forgot their password, the user is able to reset it so that they can log into the app.

**Tasks**
- [x] Implement the reset password email with Firebase Authentication

**Acceptance Criteria**
- If the user chooses that they forgot their password, an email is sent to the user with steps on how to reset password.
- The user will be able to reset the password after they follow the steps in the email.

**Comment by sjiang1** [comment]
Add the following acceptance criteria:
- The user will be able to reset the password after they follow the steps in the email.
