### ISSUE TITLE
Blocking

### ISSUE THREAD

**Issue by dhaist** [COSC481W-2022Fall/capstone-project-vibe#86]
**Description:**
As a user, I want to be able to block other users if I do not want to receive messages from them.

**Tasks:**

- [ ] Add block feature

**Acceptance Criteria:**
If a user decides to block another user, the user will not receive messages from the blocked user.

**Comment by alimo4** [comment]
- Create block list collection
- Add button to block a user in conversation view
- Include check if user is in block list before allowing message to be received
